# Generated by Django 3.0.8 on 2021-01-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('network', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('desc', models.TextField()),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
